version: '3'

services:

  dbos:
    image: mysql:5.7
    volumes:
      - mysql_storage_new:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: ronak
      MYSQL_PASSWORD: redhat
      MYSQL_DATABASE: mydb

  joomlaos:
    image: joomla:3.9-php7.2-apache
    depends_on:
      - dbos
    ports:
      - 8083:80
    volumes:
      - joomla_storage_new:/var/www/html
    restart: always
    environment:
      JOOMLA_DB_HOST: dbos:3306
      JOOMLA_DB_USER: ronak
      JOOMLA_DB_PASSWORD: redhat
      JOOMLA_DB_NAME: mydb



volumes:
  mysql_storage_new:
  joomla_storage_new:
